services:  
  weather-service:
    build: .  
    ports:
      - "8000:8000"  
    environment:  
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}  
      - REDIS_URL=redis://redis:6379/0  
    depends_on:  
      - redis  

  redis:  
    image: redis:alpine  
    ports:  
      - "6379:6379"  